// app/layout.js or app/layout.tsx
import { Geist, Geist_Mono } from 'next/font/google'
import ClientLayout from './ClientLayout'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Use metadata in a server-side context
export const metadata = {
  title: 'To do task App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900`}
      >
        <main className='lg:max-w-[80rem] mx-auto mt-2 dark:bg-gray-900'>
          <ClientLayout>{children}</ClientLayout>
        </main>
      </body>
    </html>
  )
}
